version: "3.9"
services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  session-service:
    build: ./session-service
    container_name: session-service
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "3003:3003"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "3005:3005"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  feedback-service:
    build: ./feedback-service
    container_name: feedback-service
    ports:
      - "3006:3006"
    environment:
      MONGODB_URI: "mongodb+srv://infosumitkumar3322_db_user:aAAwuVWdYLZhSuoX@cluster0.0bojjbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGODB_DB: "moodlift"
      NODE_ENV: "development"
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    depends_on:
      - user-service
      - session-service
      - chat-service
      - payment-service
      - ai-service
      - feedback-service
    restart: unless-stopped
